openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /admin/manage-users/:
    get:
      operationId: admin_manage_users_retrieve
      tags:
      - admin
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
