# Generated by Django 5.0.6 on 2026-04-18 16:47

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_id',
            field=models.CharField(help_text='e.g. dQw4w9WgXcQ', max_length=20),
        ),
        migrations.CreateModel(
            name='BikeColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Racing Red, Pearl White', max_length=100)),
                ('color_hex', models.CharField(default='#cccccc', help_text='Hex color code for swatch e.g. #FF0000', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='core.bike')),
            ],
            options={
                'verbose_name': 'Bike Color',
                'verbose_name_plural': 'Bike Colors',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BikeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image_upload', '📁 Image Upload  (JPG / PNG / GIF / WebP / BMP / SVG)'), ('image_url', '🔗 Image URL     (Google Drive / Photos / any direct link)'), ('gif_upload', '🎞 GIF Upload'), ('video_upload', '📁 Video Upload  (MP4 / WebM / MOV / AVI)'), ('video_url', '🔗 Video URL     (MP4 / WebM direct link or Google Drive)'), ('youtube', '▶  YouTube Link  (any youtube.com / youtu.be format)')], default='image_upload', max_length=20)),
                ('image_file', models.FileField(blank=True, help_text='Upload JPG, PNG, GIF, WebP, BMP, SVG', null=True, upload_to='bikes/images/', validators=[core.models.validate_image_file])),
                ('video_file', models.FileField(blank=True, help_text='Upload MP4, WebM, MOV, AVI, MKV', null=True, upload_to='bikes/videos/', validators=[core.models.validate_video_file])),
                ('media_link', models.URLField(blank=True, help_text='Image URL  →  any direct .jpg/.png/.gif link or Google Drive: https://drive.google.com/uc?export=view&id=FILE_ID  |  Video URL  →  direct .mp4 link or Google Drive video link  |  YouTube    →  https://youtube.com/watch?v=xxx  or  https://youtu.be/xxx', max_length=1000, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.bikecolor')),
            ],
            options={
                'verbose_name': 'Bike Media',
                'verbose_name_plural': 'Bike Media',
                'ordering': ['order'],
            },
        ),
    ]
