# Generated by Django 5.0.6 on 2026-04-23 09:21

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_youtubevideo_youtube_id_bikecolor_bikeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('phone2', models.CharField(blank=True, max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp number with country code, no + sign. e.g. 919953807755', max_length=15)),
                ('email', models.EmailField(blank=True, help_text='Service booking notifications go here', max_length=254)),
                ('google_maps_url', models.URLField(blank=True)),
                ('google_maps_embed', models.TextField(blank=True)),
                ('working_hours', models.CharField(default='Mon, Wed–Sun: 9:00 AM – 6:00 PM | Tuesday Closed', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Service Station',
                'verbose_name_plural': 'Service Stations',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='servicebooking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Service Booking', 'verbose_name_plural': 'Service Bookings'},
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='showroom',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number WITH country code, no + sign. e.g. 919953807755', max_length=15),
        ),
        migrations.AlterField(
            model_name='bikecolor',
            name='color_hex',
            field=models.CharField(default='#cccccc', max_length=7),
        ),
        migrations.AlterField(
            model_name='bikecolor',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bikeimage',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='bikes/images/', validators=[core.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='bikeimage',
            name='media_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bikeimage',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='bikes/videos/', validators=[core.models.validate_video_file]),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='showroom',
            field=models.ForeignKey(blank=True, help_text='Preferred showroom (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.showroom'),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='email',
            field=models.EmailField(blank=True, help_text='Enquiries from this showroom go here', max_length=254),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='google_maps_embed',
            field=models.TextField(blank=True, help_text='Paste full Google Maps iframe embed code'),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='phone',
            field=models.CharField(help_text='Primary contact number', max_length=20),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='phone2',
            field=models.CharField(blank=True, help_text='Secondary number (optional)', max_length=20),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='working_hours',
            field=models.CharField(default='Mon–Sun: 10:00 AM – 6:30 PM | Tuesday Off', max_length=150),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='service_station',
            field=models.ForeignKey(blank=True, help_text='Select the service station for the appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.servicestation'),
        ),
    ]
