# Generated by Django 5.0.6 on 2026-04-23 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_servicestation_alter_servicebooking_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicestation',
            name='manager',
            field=models.OneToOneField(blank=True, help_text="This user can only see this station's data in admin", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_station', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='showroom',
            name='manager',
            field=models.OneToOneField(blank=True, help_text="This user can only see this showroom's data in admin", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_showroom', to=settings.AUTH_USER_MODEL),
        ),
    ]
