# Generated by Django 5.0.6 on 2026-04-24 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_servicestation_manager_showroom_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikeimage',
            name='bike',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='all_media', to='core.bike'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bikeimage',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.bikecolor'),
        ),
    ]
