# Generated by Django 5.0.6 on 2026-04-24 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bikeimage_bike_alter_bikeimage_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='service_station',
            field=models.ForeignKey(blank=True, help_text='Select if it is a standalone service station', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.servicestation'),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='showroom',
            field=models.ForeignKey(blank=True, help_text='Select the Showroom if they provide service', limit_choices_to={'has_service_center': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.showroom'),
        ),
    ]
