# Generated by Django 5.0.6 on 2026-04-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_servicebooking_service_station_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='showroom',
            name='has_service_center',
            field=models.BooleanField(default=False, help_text='Showroom provides service'),
        ),
    ]
