# Generated by Django 5.0.6 on 2026-04-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_showroom_has_service_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikeimage',
            name='media_type',
            field=models.CharField(choices=[('image_upload', '📁 Image Upload'), ('image_url', '🔗 Image URL'), ('gif_upload', '🎞 GIF Upload'), ('video_upload', '📁 Video Upload'), ('video_url', '🔗 Video URL'), ('youtube', '▶  YouTube Link')], default='image_upload', max_length=20),
        ),
    ]
