# Generated by Django 5.0.6 on 2026-04-25 10:23

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_bikeimage_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='image',
            field=models.ImageField(blank=True, help_text='Main thumbnail image for the bike listing', null=True, upload_to='bikes/'),
        ),
        migrations.AlterField(
            model_name='bikecolor',
            name='color_hex',
            field=models.CharField(default='#cccccc', help_text='Hex color code e.g. #ff0000', max_length=7),
        ),
        migrations.AlterField(
            model_name='bikeimage',
            name='bike',
            field=models.ForeignKey(blank=True, help_text='Auto-filled from color if left empty', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_media', to='core.bike'),
        ),
        migrations.AlterField(
            model_name='bikeimage',
            name='color',
            field=models.ForeignKey(blank=True, help_text='Assign to a specific color variant, or leave blank for generic bike media', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.bikecolor'),
        ),
        migrations.AlterField(
            model_name='bikeimage',
            name='image_file',
            field=models.FileField(blank=True, help_text='Upload image/GIF file (jpg, png, gif, webp, heic, svg, bmp)', null=True, upload_to='bikes/images/', validators=[core.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='bikeimage',
            name='media_link',
            field=models.URLField(blank=True, help_text='Paste image URL, Google Drive share link, video URL, or YouTube URL', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bikeimage',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file (mp4, webm, mov, avi, mkv, ogg)', null=True, upload_to='bikes/videos/', validators=[core.models.validate_video_file]),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='bike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='core.bike'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='showroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='core.showroom'),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='interested_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_requests', to='core.bike'),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='showroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_requests', to='core.showroom'),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='service_station',
            field=models.ForeignKey(blank=True, help_text='Select a standalone service station (leave blank if using a showroom)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_bookings', to='core.servicestation'),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='showroom',
            field=models.ForeignKey(blank=True, help_text='Select a showroom that provides service (leave blank if using a service station)', limit_choices_to={'has_service_center': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_bookings', to='core.showroom'),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='has_service_center',
            field=models.BooleanField(default=False, help_text='Check if this showroom provides service'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_id',
            field=models.CharField(help_text='YouTube video ID only, e.g. dQw4w9WgXcQ', max_length=20),
        ),
    ]
