# Generated by Django 5.0.6 on 2026-05-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='is_chetak',
            field=models.BooleanField(default=False, help_text='Check for Chetak electric scooters — shown on Chetak page only, hidden from main bikes list'),
        ),
    ]
