# Generated by Django 5.0.6 on 2026-05-20 08:04

from django.db import migrations, models
from django.utils.text import slugify


def fill_servicestation_slugs(apps, schema_editor):
    ServiceStation = apps.get_model('core', 'ServiceStation')
    for obj in ServiceStation.objects.all():
        base = slugify(obj.name)
        slug, n = base, 1
        while ServiceStation.objects.filter(slug=slug).exists():
            slug = f"{base}-{n}"; n += 1
        obj.slug = slug
        obj.save(update_fields=['slug'])


def fill_showroom_slugs(apps, schema_editor):
    Showroom = apps.get_model('core', 'Showroom')
    for obj in Showroom.objects.all():
        base = slugify(obj.name)
        slug, n = base, 1
        while Showroom.objects.filter(slug=slug).exists():
            slug = f"{base}-{n}"; n += 1
        obj.slug = slug
        obj.save(update_fields=['slug'])


class Migration(migrations.Migration):
    atomic = False 

    dependencies = [
        ('core', '0011_bike_is_chetak'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Optional. Custom SEO description (max 160 chars). Leave blank to auto-generate.', max_length=160),
        ),
        migrations.AddField(
            model_name='bike',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Optional. Custom SEO title (max 70 chars). Leave blank to auto-generate.', max_length=70),
        ),
        migrations.AddField(
            model_name='servicestation',
            name='city',
            field=models.CharField(blank=True, help_text='City name e.g. Noida, Greater Noida', max_length=100),
        ),
        # Step 1: add without unique
        migrations.AddField(
            model_name='servicestation',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='Auto-filled from name if left blank.', unique=False),
            preserve_default=False,
        ),
        # Step 2: populate
        migrations.RunPython(fill_servicestation_slugs, migrations.RunPython.noop),
        # Step 3: enforce unique
        migrations.AlterField(
            model_name='servicestation',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-filled from name if left blank.', unique=True),
        ),
        migrations.AddField(
            model_name='showroom',
            name='city',
            field=models.CharField(blank=True, help_text='City name shown in footer showroom list e.g. Noida, Greater Noida', max_length=100),
        ),
        # Step 1: add without unique
        migrations.AddField(
            model_name='showroom',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='Auto-filled from name if left blank. Used in anchor links on contact page.', unique=False),
            preserve_default=False,
        ),
        # Step 2: populate
        migrations.RunPython(fill_showroom_slugs, migrations.RunPython.noop),
        # Step 3: enforce unique
        migrations.AlterField(
            model_name='showroom',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-filled from name if left blank. Used in anchor links on contact page.', unique=True),
        ),
    ]